name: JMPS
version: ${project.version}
main: org.aoichaan0513.jmps.Main

commands:
  warn:
  unwarn:
  mute:
  unmute:
  kick:
  ban:
  unban:
  tban:
  untban:
  gban:
  ungban:

  admin:
  staff:
  whois:
  namelookup: